import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, { createContext, useContext } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// --- Sound Context ---
const ButtonSoundContext = createContext<() => void>(() => {});

export function useButtonSound() {
  return useContext(ButtonSoundContext);
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // You can use your own sound file here (public/click.mp3)
  const playSound = () => {
    const audio = new Audio("/click.mp3");
    audio.volume = 0.2;
    audio.play();
  };

  // Wrap children in context provider and inject a global button handler
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ButtonSoundContext.Provider value={playSound}>
          <div
            onClick={(e) => {
              const target = e.target as HTMLElement;
              if (target.tagName === "BUTTON") playSound();
            }}
          >
            {children}
          </div>
        </ButtonSoundContext.Provider>
      </body>
    </html>
  );
}
